import I0 from "../../images/LATF/0.jpg";
import I1 from "../../images/LATF/1.jpg";
import I2 from "../../images/LATF/2.jpg";
import I3 from "../../images/LATF/3.jpg";
import I4 from "../../images/LATF/4.jpg";
import I5 from "../../images/LATF/5.jpg";
import I6 from "../../images/LATF/6.jpg";
import I7 from "../../images/LATF/7.jpg";
import I8 from "../../images/LATF/8.jpg";
import I9 from "../../images/LATF/9.jpg";
import I10 from "../../images/LATF/10.jpg";
import I11 from "../../images/LATF/11.jpg";
import I12 from "../../images/LATF/12.jpg";
import I13 from "../../images/LATF/13.jpg";
import I14 from "../../images/LATF/14_text.jpg";
import I14a from "../../images/LATF/14a.jpg";
import I14a1 from "../../images/LATF/14a1.jpg";
import I14a2 from "../../images/LATF/14a2.jpg";
import I14a3 from "../../images/LATF/14a3.jpg";
import I14a4 from "../../images/LATF/14a4.jpg";
import I14a5 from "../../images/LATF/14a5.jpg";
import I14a6 from "../../images/LATF/14a6_text.jpg";
import I15 from "../../images/LATF/15.jpg";
import I16 from "../../images/LATF/16.jpg";
import I17 from "../../images/LATF/17.jpg";
import I18 from "../../images/LATF/18.jpg";
import I19 from "../../images/LATF/19.jpg";
import I20 from "../../images/LATF/20.jpg";
import I21 from "../../images/LATF/21.jpg";
import I22 from "../../images/LATF/22.jpg";
import I23 from "../../images/LATF/23.jpg";
import I24 from "../../images/LATF/24.jpg";
import I25 from "../../images/LATF/25_text.jpg";
import I26 from "../../images/LATF/26.jpg";
import I27 from "../../images/LATF/27.jpg";
import I28 from "../../images/LATF/28.jpg";
import I29 from "../../images/LATF/29.jpg";
import I30 from "../../images/LATF/30.jpg";
import I31 from "../../images/LATF/31.jpg";
import I32 from "../../images/LATF/32.jpg";
import I33 from "../../images/LATF/33.jpg";
import I34 from "../../images/LATF/34.jpg";
import I35 from "../../images/LATF/35.jpg";
import I36 from "../../images/LATF/36.jpg";
import I37 from "../../images/LATF/37.jpg";
// import I38 from "../../images/LATF/38.jpg";
import I39 from "../../images/LATF/39.jpg";
import I40 from "../../images/LATF/40.jpg";
import I41 from "../../images/LATF/41.jpg";
import I42 from "../../images/LATF/42.jpg";
import I43 from "../../images/LATF/43_text.jpg";
import I44 from "../../images/LATF/44.jpg";
import I45 from "../../images/LATF/45.jpg";
import I46 from "../../images/LATF/46.jpg";
import I47 from "../../images/LATF/47.jpg";
import I48 from "../../images/LATF/48.jpg";
import I49 from "../../images/LATF/49.jpg";
import I50 from "../../images/LATF/50_text.jpg";
import I51 from "../../images/LATF/51.jpg";
import I52 from "../../images/LATF/52.jpg";
import I53 from "../../images/LATF/53.jpg";
import I54 from "../../images/LATF/54.jpg";
import I55 from "../../images/LATF/55.jpg";
import I56 from "../../images/LATF/56.jpg";
import I57 from "../../images/LATF/57.jpg";
import I58 from "../../images/LATF/58.jpg";
import I59 from "../../images/LATF/59.jpg";
import I60 from "../../images/LATF/60.jpg";
import I61 from "../../images/LATF/61.jpg";
import I62 from "../../images/LATF/62.jpg";
import I63 from "../../images/LATF/63.jpg";
import I64 from "../../images/LATF/64.jpg";
import I65 from "../../images/LATF/65.jpg";
import I66 from "../../images/LATF/66.jpg";
import I67 from "../../images/LATF/67_text.jpg";
import I68 from "../../images/LATF/68.jpg";
// import I69 from "../../images/LATF/69.jpg";
import I70 from "../../images/LATF/70.jpg";
import I71 from "../../images/LATF/71.jpg";
import I72 from "../../images/LATF/72.jpg";
import I73 from "../../images/LATF/73_text.jpg";
import I74 from "../../images/LATF/74.jpg";

export const FirstBlock = [
  {
    id: 1,
    pic: I1,
    imgWidth: "20%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "24%",
    positionX: "",
    speed: 30,
  },
  {
    id: 2,
    pic: I2,
    imgWidth: "56%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: -30,
  },
  {
    id: 3,
    pic: I3,
    imgWidth: "50%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    id: 4,
    pic: I4,
    imgWidth: "16%",
    mTop: "",
    mRight: "10%",
    mBottom: "",
    mLeft: "24%",
    positionX: "flex-end",
    speed: -20,
  },
  {
    id: 5,
    pic: I5,
    imgWidth: "26%",
    mTop: "",
    mRight: "20%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: -10,
  },
  {
    id: 6,
    pic: I6,
    imgWidth: "100%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    id: 7,
    pic: I7,
    imgWidth: "16%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "20%",
    positionX: "",
    speed: 5,
  },
  {
    id: 8,
    pic: I8,
    imgWidth: "50%",
    mTop: "30%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: -3,
  },
  {
    id: 9,
    pic: I9,
    imgWidth: "50%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 0,
  },
];
export const SecondBlock = [
  {
    id: 11,
    pic: I11,
    imgWidth: "70%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    id: 12,
    pic: I12,
    imgWidth: "80%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 6,
  },
  {
    id: 13,
    pic: I13,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
];
export const ThirdBlock = [
  {
    pic: I14a,
    imgWidth: "100%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    pic: I14a1,
    imgWidth: "30%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 6,
  },
  {
    pic: I14a2,
    imgWidth: "60%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I14a3,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "5%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I14a4,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I14a5,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 2.5,
  },
];
export const FourthBlock = [
  {
    pic: I15,
    imgWidth: "100%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    pic: I16,
    imgWidth: "30%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 6,
  },
  {
    pic: I17,
    imgWidth: "60%",
    mTop: "-40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I18,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "5%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I19,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I20,
    imgWidth: "100%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I21,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I22,
    imgWidth: "80%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I23,
    imgWidth: "100%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I24,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
];
export const FifthBlock = [
  {
    pic: I26,
    imgWidth: "40%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    pic: I27,
    imgWidth: "100%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 6,
  },
  {
    pic: I28,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "10%",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I29,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "10%",
    mBottom: "",
    mLeft: "5%",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I30,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 2.5,
  },
  {
    pic: I31,
    imgWidth: "100%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 5,
  },
  {
    pic: I32,
    imgWidth: "30%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 6,
  },
  {
    pic: I33,
    imgWidth: "30%",
    mTop: "-30%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I34,
    imgWidth: "70%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I35,
    imgWidth: "50%",
    mTop: "",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I36,
    imgWidth: "60%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I37,
    imgWidth: "100%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  // {
  //   pic: I38,
  //   imgWidth: "60%",
  //   mTop: "40%",
  //   mRight: "",
  //   mBottom: "",
  //   mLeft: "",
  //   positionX: "",
  //   speed: 2.5,
  // },
  {
    pic: I39,
    imgWidth: "30%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I40,
    imgWidth: "50%",
    mTop: "-10%",
    mRight: "",
    mBottom: "",
    mLeft: "10%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I41,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I42,
    imgWidth: "100%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
];
export const SixthBlock = [
  {
    pic: I44,
    imgWidth: "100%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I45,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I46,
    imgWidth: "50%",
    mTop: "20%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I47,
    imgWidth: "60%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I48,
    imgWidth: "100%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I49,
    imgWidth: "60%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
];
export const SeventhBlock = [
  {
    pic: I51,
    imgWidth: "100%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I52,
    imgWidth: "60%",
    mTop: "40%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 2.5,
  },
  {
    pic: I53,
    imgWidth: "30%",
    mTop: "20%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I54,
    imgWidth: "50%",
    mTop: "10%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I55,
    imgWidth: "60%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "5%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I56,
    imgWidth: "20%",
    mTop: "40%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I57,
    imgWidth: "30%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I58,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "2%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I59,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I60,
    imgWidth: "30%",
    mTop: "40%",
    mRight: "4%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I61,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "",
    mBottom: "10%",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I62,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "5%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I63,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "14%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I64,
    imgWidth: "60%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I65,
    imgWidth: "40%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "18%",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I66,
    imgWidth: "85%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
];
export const EighthBlock = [
  {
    pic: I68,
    imgWidth: "30%",
    mTop: "5%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  // {
  //   pic: I69,
  //   imgWidth: "30%",
  //   mTop: "5%",
  //   mRight: "",
  //   mBottom: "",
  //   mLeft: "",
  //   positionX: "",
  //   speed: 2.5,
  // },
  {
    pic: I70,
    imgWidth: "70%",
    mTop: "20%",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    pic: I71,
    imgWidth: "10%",
    mTop: "10%",
    mRight: "8%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 2.5,
  },
  {
    pic: I72,
    imgWidth: "50%",
    mTop: "40%",
    mRight: "",
    mBottom: "",
    mLeft: "5%",
    positionX: "center",
    speed: 2.5,
  },
];
export const SubPage = [
  {
    id: 0,
    pic: I10,
    imgWidth: "80%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 0,
  },

  {
    id: 1,
    pic: I14,
    imgWidth: "80%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 0,
  },

  {
    id: 2,
    pic: I14a6,
    imgWidth: "80%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "center",
    speed: 0,
  },
  {
    id: 3,
    pic: I25,
    imgWidth: "16%",
    mTop: "",
    mRight: "10%",
    mBottom: "",
    mLeft: "24%",
    positionX: "flex-end",
    speed: -20,
  },
  {
    id: 4,
    pic: I43,
    imgWidth: "26%",
    mTop: "",
    mRight: "20%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: -10,
  },
  {
    id: 5,
    pic: I50,
    imgWidth: "100%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "",
    positionX: "",
    speed: 2.5,
  },
  {
    id: 6,
    pic: I67,
    imgWidth: "16%",
    mTop: "100px",
    mRight: "",
    mBottom: "",
    mLeft: "20%",
    positionX: "",
    speed: 5,
  },
  {
    id: 7,
    pic: I73,
    imgWidth: "50%",
    mTop: "30%",
    mRight: "10%",
    mBottom: "",
    mLeft: "",
    positionX: "flex-end",
    speed: 0,
  },
];
